"""add_id_hashed_and_products_hashed

Revision ID: 42d59d204dfc
Revises: e26fcac0d4bf
Create Date: 2024-09-28 18:18:46.675339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d59d204dfc'
down_revision: Union[str, None] = 'e26fcac0d4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('id_hashed', sa.String(length=64), nullable=True))
    op.add_column('stores', sa.Column('products_hashed', sa.String(length=64), nullable=True))
    op.add_column('stores', sa.Column('embedded', sa.Boolean(), nullable=True))
    op.drop_column('stores', 'hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('stores', 'embedded')
    op.drop_column('stores', 'products_hashed')
    op.drop_column('stores', 'id_hashed')
    # ### end Alembic commands ###
