"""add_embedding_index_path

Revision ID: 8548c609d232
Revises: 42d59d204dfc
Create Date: 2024-09-29 13:15:46.776702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8548c609d232'
down_revision: Union[str, None] = '42d59d204dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('embbded_index_path', sa.String(), nullable=True))
    op.alter_column('stores', 'id_hashed',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_unique_constraint(None, 'stores', ['id_hashed'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='unique')
    op.alter_column('stores', 'id_hashed',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('stores', 'embbded_index_path')
    # ### end Alembic commands ###
