"""change_length_of_id

Revision ID: a8919592511a
Revises: 9605a81c8b45
Create Date: 2024-10-03 15:04:45.254203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8919592511a'
down_revision: Union[str, None] = '9605a81c8b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=70),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'id',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
