"""add date field and extend id

Revision ID: e26fcac0d4bf
Revises: fe9d50648384
Create Date: 2024-08-30 07:26:00.935201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26fcac0d4bf'
down_revision: Union[str, None] = 'fe9d50648384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('stores', 'id',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'id',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)
    op.drop_column('stores', 'updated_at')
    # ### end Alembic commands ###
