"""add_some_fields

Revision ID: fe9d50648384
Revises: 62a8050fd2a8
Create Date: 2024-08-28 07:34:34.441309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9d50648384'
down_revision: Union[str, None] = '62a8050fd2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('stores', sa.Column('kind', sa.String(length=50), nullable=True))
    op.alter_column('stores', 'products',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stores', 'hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('stores', 'products',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('stores', 'kind')
    op.drop_column('stores', 'name')
    # ### end Alembic commands ###
